<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="MT_Test" targetNamespace="TestMMUpload" xmlns:p1="TestMMUpload" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"><wsdl:documentation/><wsdl:types><xsd:schema targetNamespace="TestMMUpload" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="TestMMUpload"><xsd:element name="MT_Test" type="DT_Test"/><xsd:complexType name="DT_Test"><xsd:annotation><xsd:appinfo source="http://sap.com/xi/VersionID">6ed7db258f1411ec948c000000942ef6</xsd:appinfo></xsd:annotation><xsd:sequence><xsd:element name="Field1" type="xsd:string" minOccurs="0"/><xsd:element name="Field2" type="xsd:string" minOccurs="0"/></xsd:sequence></xsd:complexType></xsd:schema></wsdl:types><wsdl:message name="MT_Test"><wsdl:documentation/><wsdl:part name="MT_Test" element="p1:MT_Test"/></wsdl:message></wsdl:definitions>